### ISSUE TITLE
How to use it with vue ?

### ISSUE THREAD

**Issue by akeshj** [PDFTron/webviewer-electron-sample#4]
In my application i use both vue and elctron , I run the application in vue and electron so how I can combined this code with vue?

**Comment by mparizeau-pdftron** [comment]
Electron should work together with Vue https://www.digitalocean.com/community/tutorials/vuejs-vue-electron

These sample projects show some examples with different frameworks but at the end of the day there isn't any magic happening with a particular framework. Here are the general steps you need to handle https://www.pdftron.com/documentation/web/frameworks/#integrating-into-other-frameworks

Basically referencing the WebViewer lib folder with the `path` option and passing in a DOM element for WebViewer to attach to.

**Comment by andreysaf** [comment]
We have updated the sample even further, to make it easier to get started. Let me know if you have any questions.
