### ISSUE TITLE
doesnt work with electron .

### ISSUE THREAD

**Issue by asadadams** [PDFTron/webviewer-electron-sample#6]
When starting app with "electron ." it doesnt work

**Comment by andreysaf** [comment]
Hello @asadadams, thanks for reaching out! 

Could you run it via `npm run start`? The start script then triggers: `"start": "electron-forge start",`

It uses electron forge instead of electron.

**Comment by asadadams** [comment]
It works with electron forge , don't know why it doesn't work with electron . Do you know why

**Comment by andreysaf** [comment]
I think Electron Forge has some additional dependencies, and from what I heard Electron Forge is the way to go nowadays. I have a commit here before we switched to Electron Forge. 

You can rollback to this commit:
https://github.com/PDFTron/webviewer-electron-sample/commit/a8a643786909f72905a5d4f558fc3ab5387abe7d

**Comment by asadadams** [comment]
@andreysaf thank you very much
