### ISSUE TITLE
Pricing to use 

### ISSUE THREAD

**Issue by zmap95** [PDFTron/webviewer-electron-sample#8]
Hi sir, 
I wanna to use this source code to build internal application (feature like your video https://youtu.be/FyZ40lNE-pY).
Do I need to buy the license ?

**Comment by mparizeau-pdftron** [comment]
Hi, yes you would need to buy a license and you can contact our sales team to get more information on pricing https://apryse.com/form/contact-sales

Note that you are also welcome to use the trial as long as you need while you test and work on your application.
